In [25]:
import pandas as pd
import pickle
import copy
from collections import Counter

In [3]:
reload = False
if reload:
    sentiment_factors = pd.read_csv('./ALL.csv')
    with open('sentiment_factors.pkl','wb') as f:
        pickle.dump(sentiment_factors, f, pickle.HIGHEST_PROTOCOL)

In [4]:
with open('sentiment_factors.pkl', 'rb') as f:
    sentiment_factors = pickle.load(f)

In [5]:
with open('market_factors_earning_enhanced.pkl', 'rb') as f:
    market_factors = pickle.load(f)

In [6]:
sentiment_factors.shape

(485498, 49)

In [7]:
market_factors.shape

(4064834, 52)

In [8]:
market_factors['datetime'] = market_factors['time'].apply(lambda x:x[:10])

In [9]:
sentiment_factors.columns

Index(['datetime', 'assetCode', 'month', 'week', 'alert', 'article',
       'alert_relevance_weighted_sentiment',
       'alert_relevance_weighted_negative_sentiment',
       'alert_relevance_weighted_positive_sentiment',
       'alert_relevance_weighted_neutral_sentiment',
       'alert_news_volume_sum_12H', 'alert_news_novelty_sum_12H',
       'alert_news_volume_sum_24H', 'alert_news_novelty_sum_24H',
       'alert_news_volume_sum_3D', 'alert_news_novelty_sum_3D',
       'alert_news_volume_sum_5D', 'alert_news_novelty_sum_5D',
       'alert_news_volume_sum_7D', 'alert_news_novelty_sum_7D',
       'article_relevance_weighted_sentiment',
       'article_relevance_weighted_negative_sentiment',
       'article_relevance_weighted_positive_sentiment',
       'article_relevance_weighted_neutral_sentiment',
       'article_news_volume_sum_12H', 'article_news_novelty_sum_12H',
       'article_news_volume_sum_24H', 'article_news_novelty_sum_24H',
       'article_news_volume_sum_3D', 'article_news_novelty_sum_3D',
       'article_news_volume_sum_5D', 'article_news_novelty_sum_5D',
       'article_news_volume_sum_7D', 'article_news_novelty_sum_7D',
       'relevance_weighted_sentiment', 'relevance_weighted_negative_sentiment',
       'relevance_weighted_positive_sentiment',
       'relevance_weighted_neutral_sentiment', 'news_volume_sum_12H',
       'news_novelty_sum_12H', 'news_volume_sum_24H', 'news_novelty_sum_24H',
       'news_volume_sum_3D', 'news_novelty_sum_3D', 'news_volume_sum_5D',
       'news_novelty_sum_5D', 'news_volume_sum_7D', 'news_novelty_sum_7D',
       'returnsOpenNextMktres10'],
      dtype='object')

In [10]:
market_factors.columns

Index(['index', 'Unnamed: 0', 'time', 'assetCode', 'assetName', 'volume',
       'close', 'open', 'returnsClosePrevRaw1', 'returnsOpenPrevRaw1',
       'returnsClosePrevMktres1', 'returnsOpenPrevMktres1',
       'returnsClosePrevRaw10', 'returnsOpenPrevRaw10',
       'returnsClosePrevMktres10', 'returnsOpenPrevMktres10',
       'returnsOpenNextMktres10', 'universe', 'returnsVolumePrev1',
       'returnsVolumePrev10', 'CloseMA5', 'CloseMA10', 'CloseMA20',
       'returnsCloseMA5', 'returnsCloseMA10', 'returnsCloseMA20', 'VolumeMA5',
       'VolumeMA10', 'VolumeMA20', 'returnsVolumeMA5', 'returnsVolumeMA10',
       'returnsVolumeMA20', 'date', 'earning_period_flag', 'reversal',
       'modified_earning_flag', 'reverse_returnsClosePrevRaw1',
       'reverse_returnsOpenPrevRaw1', 'reverse_returnsClosePrevMktres1',
       'reverse_returnsOpenPrevMktres1', 'reverse_returnsCloseMA5',
       'reverse_VolumeMA5', 'reverse_VolumeMA10', 'reverse_VolumeMA20',
       'earnings_enhanced_reverse_returnsClosePrevRaw1',
       'earnings_enhanced_reverse_returnsOpenPrevRaw1',
       'earnings_enhanced_reverse_returnsClosePrevMktres1',
       'earnings_enhanced_reverse_returnsOpenPrevMktres1',
       'earnings_enhanced_reverse_returnsCloseMA5',
       'earnings_enhanced_reverse_VolumeMA5',
       'earnings_enhanced_reverse_VolumeMA10',
       'earnings_enhanced_reverse_VolumeMA20', 'datetime'],
      dtype='object')

In [11]:
sentiment_factors[['datetime', 'assetCode']]

          datetime assetCode
0       2007-02-01       A.N
1       2007-02-01     MRO.N
2       2007-02-01      MS.N
3       2007-02-01    MSFT.O
4       2007-02-01     MYL.N
5       2007-02-01    NDAQ.O
6       2007-02-01     NKE.N
7       2007-02-01     NMX.N
8       2007-02-01     NOC.N
9       2007-02-01      MO.N
10      2007-02-01     NOK.N
11      2007-02-01     NVS.N
12      2007-02-01     NYT.N
13      2007-02-01     OMC.N
14      2007-02-01      PD.N
15      2007-02-01     PFE.N
16      2007-02-01     PFG.N
17      2007-02-01      PG.N
18      2007-02-01     PKI.N
19      2007-02-01    NVDA.O
20      2007-02-01     PKX.N
21      2007-02-01     MMC.N
22      2007-02-01     MCO.N
23      2007-02-01     HSY.N
24      2007-02-01     IBM.N
25      2007-02-01    JBLU.O
26      2007-02-01     JCP.N
27      2007-02-01     JEC.N
28      2007-02-01     JNC.N
29      2007-02-01     JNJ.N
...            ...       ...
485468  2016-12-30     ABX.N
485469  2016-12-30     ADI.O
485470  2016-12-30     ADM.N
485471  2016-12-30     AGN.N
485472  2016-12-30    AMAT.O
485473  2016-12-30    AMZN.O
485474  2016-12-30    ASML.O
485475  2016-12-30    BABA.N
485476  2016-12-30     BBL.N
485477  2016-12-30     BCS.N
485478  2016-12-30      BG.N
485479  2016-12-30     BHI.N
485480  2016-12-30      GS.N
485481  2016-12-30     BHP.N
485482  2016-12-30     CNI.N
485483  2016-12-30    CRUS.O
485484  2016-12-30      CS.N
485485  2016-12-30     CVX.N
485486  2016-12-30     DAL.N
485487  2016-12-30      DB.N
485488  2016-12-30     DIS.N
485489  2016-12-30    DISH.O
485490  2016-12-30     ENB.N
485491  2016-12-30    ENDP.O
485492  2016-12-30    ESRX.O
485493  2016-12-30      FB.O
485494  2016-12-30     FCX.N
485495  2016-12-30    FOXA.O
485496  2016-12-30       C.N
485497  2016-12-30     WPZ.N

[485498 rows x 2 columns]

In [12]:
market_factors[[ 'datetime', 'assetCode']]

           datetime assetCode
0        2007-02-01       A.N
1        2007-02-01     AAI.N
2        2007-02-01     AAP.N
3        2007-02-01    AAPL.O
4        2007-02-01     ABB.N
5        2007-02-01     ABC.N
6        2007-02-01     ABD.N
7        2007-02-01     ABM.N
8        2007-02-01     ABT.N
9        2007-02-01     ABV.N
10       2007-02-01     ABY.N
11       2007-02-01     ACF.N
12       2007-02-01     ACH.N
13       2007-02-01     ACL.N
14       2007-02-01     ACS.N
15       2007-02-01    ACTS.O
16       2007-02-01    ACXM.O
17       2007-02-01      AD.N
18       2007-02-01    ADBE.O
19       2007-02-01    ADCT.O
20       2007-02-01     ADI.N
21       2007-02-01     ADM.N
22       2007-02-01     ADP.N
23       2007-02-01     ADS.N
24       2007-02-01    ADSK.O
25       2007-02-01    ADTN.O
26       2007-02-01     AEA.N
27       2007-02-01     AEE.N
28       2007-02-01     AEG.N
29       2007-02-01    AEIS.O
...             ...       ...
4064804  2016-12-30    XLNX.O
4064805  2016-12-30    XLRN.O
4064806  2016-12-30    XNCR.O
4064807  2016-12-30     XOG.O
4064808  2016-12-30     XOM.N
4064809  2016-12-30     XON.N
4064810  2016-12-30     XPO.N
4064811  2016-12-30    XRAY.O
4064812  2016-12-30    XXIA.O
4064813  2016-12-30     XYL.N
4064814  2016-12-30    YELP.N
4064815  2016-12-30    YHOO.O
4064816  2016-12-30    YNDX.O
4064817  2016-12-30     YPF.N
4064818  2016-12-30     YRD.N
4064819  2016-12-30     YUM.N
4064820  2016-12-30    YUMC.N
4064821  2016-12-30      YY.O
4064822  2016-12-30       Z.O
4064823  2016-12-30    ZAYO.N
4064824  2016-12-30     ZBH.N
4064825  2016-12-30    ZBRA.O
4064826  2016-12-30     ZEN.N
4064827  2016-12-30      ZG.O
4064828  2016-12-30    ZION.O
4064829  2016-12-30    ZIOP.O
4064830  2016-12-30    ZLTQ.O
4064831  2016-12-30    ZNGA.O
4064832  2016-12-30     ZTO.N
4064833  2016-12-30     ZTS.N

[4064834 rows x 2 columns]

In [13]:
sentiment_factors.groupby(['datetime','assetCode'])['alert_relevance_weighted_sentiment'].sum()

datetime    assetCode
2007-02-01  A.N          0.000000
            ABB.N        0.000000
            ABT.N        1.000000
            ABV.N        1.000000
            ACH.N        1.000000
            ADBE.O       0.000000
            ADCT.O      -0.286423
            ADM.N        0.691113
            AFFX.O       0.000000
            AG.N         1.000000
            AGN.N       -1.000000
            ALK.N        1.000000
            AMZN.O      -0.634273
            APOL.O       0.000000
            ASN.N        0.000000
            ATI.N        0.000000
            AXP.N        1.000000
            AZN.N        0.543401
            BA.N        -0.462828
            BAC.N       -0.454164
            BBY.N        0.540663
            BCR.N        1.000000
            BCS.N       -0.022413
            BDX.N        0.000000
            BEC.N        0.000000
            BHP.N        0.309193
            BIDU.O      -1.000000
            BK.N        -1.000000
            BMC.N        1.000000
            BMY.N       -0.569369
                           ...
2016-12-30  JNJ.N        0.225233
            JPM.N       -0.720825
            LAZ.N       -1.000000
            MCK.N       -1.000000
            MFC.N        1.000000
            MON.N        1.000000
            MS.N         1.000000
            MSFT.O      -0.196157
            MU.O        -0.866323
            MYL.O        0.391459
            NEM.N        0.000000
            NFLX.O       1.000000
            NVDA.O      -0.944834
            OKE.N       -0.944834
            PDCE.O      -1.000000
            PFE.N       -0.269677
            QCOM.O      -0.603757
            QRVO.O      -1.000000
            RBS.N       -1.000000
            RDSb.N       1.000000
            RIO.N        1.000000
            SGEN.O      -1.000000
            SWKS.O      -0.866323
            T.N          1.000000
            TD.N         1.000000
            TEF.N        1.000000
            TSM.N        1.000000
            UBS.N        1.000000
            UNH.N        1.000000
            WPZ.N       -0.248780
Name: alert_relevance_weighted_sentiment, Length: 485498, dtype: float64

In [14]:
merged_factors = pd.merge(market_factors,sentiment_factors,how = 'left',left_on = ['datetime','assetCode'],right_on = ['datetime','assetCode'])

In [15]:
merged_factors.columns

Index(['index', 'Unnamed: 0', 'time', 'assetCode', 'assetName', 'volume',
       'close', 'open', 'returnsClosePrevRaw1', 'returnsOpenPrevRaw1',
       'returnsClosePrevMktres1', 'returnsOpenPrevMktres1',
       'returnsClosePrevRaw10', 'returnsOpenPrevRaw10',
       'returnsClosePrevMktres10', 'returnsOpenPrevMktres10',
       'returnsOpenNextMktres10_x', 'universe', 'returnsVolumePrev1',
       'returnsVolumePrev10', 'CloseMA5', 'CloseMA10', 'CloseMA20',
       'returnsCloseMA5', 'returnsCloseMA10', 'returnsCloseMA20', 'VolumeMA5',
       'VolumeMA10', 'VolumeMA20', 'returnsVolumeMA5', 'returnsVolumeMA10',
       'returnsVolumeMA20', 'date', 'earning_period_flag', 'reversal',
       'modified_earning_flag', 'reverse_returnsClosePrevRaw1',
       'reverse_returnsOpenPrevRaw1', 'reverse_returnsClosePrevMktres1',
       'reverse_returnsOpenPrevMktres1', 'reverse_returnsCloseMA5',
       'reverse_VolumeMA5', 'reverse_VolumeMA10', 'reverse_VolumeMA20',
       'earnings_enhanced_reverse_returnsClosePrevRaw1',
       'earnings_enhanced_reverse_returnsOpenPrevRaw1',
       'earnings_enhanced_reverse_returnsClosePrevMktres1',
       'earnings_enhanced_reverse_returnsOpenPrevMktres1',
       'earnings_enhanced_reverse_returnsCloseMA5',
       'earnings_enhanced_reverse_VolumeMA5',
       'earnings_enhanced_reverse_VolumeMA10',
       'earnings_enhanced_reverse_VolumeMA20', 'datetime', 'month', 'week',
       'alert', 'article', 'alert_relevance_weighted_sentiment',
       'alert_relevance_weighted_negative_sentiment',
       'alert_relevance_weighted_positive_sentiment',
       'alert_relevance_weighted_neutral_sentiment',
       'alert_news_volume_sum_12H', 'alert_news_novelty_sum_12H',
       'alert_news_volume_sum_24H', 'alert_news_novelty_sum_24H',
       'alert_news_volume_sum_3D', 'alert_news_novelty_sum_3D',
       'alert_news_volume_sum_5D', 'alert_news_novelty_sum_5D',
       'alert_news_volume_sum_7D', 'alert_news_novelty_sum_7D',
       'article_relevance_weighted_sentiment',
       'article_relevance_weighted_negative_sentiment',
       'article_relevance_weighted_positive_sentiment',
       'article_relevance_weighted_neutral_sentiment',
       'article_news_volume_sum_12H', 'article_news_novelty_sum_12H',
       'article_news_volume_sum_24H', 'article_news_novelty_sum_24H',
       'article_news_volume_sum_3D', 'article_news_novelty_sum_3D',
       'article_news_volume_sum_5D', 'article_news_novelty_sum_5D',
       'article_news_volume_sum_7D', 'article_news_novelty_sum_7D',
       'relevance_weighted_sentiment', 'relevance_weighted_negative_sentiment',
       'relevance_weighted_positive_sentiment',
       'relevance_weighted_neutral_sentiment', 'news_volume_sum_12H',
       'news_novelty_sum_12H', 'news_volume_sum_24H', 'news_novelty_sum_24H',
       'news_volume_sum_3D', 'news_novelty_sum_3D', 'news_volume_sum_5D',
       'news_novelty_sum_5D', 'news_volume_sum_7D', 'news_novelty_sum_7D',
       'returnsOpenNextMktres10_y'],
      dtype='object')

In [20]:
merged_factors['alert'].fillna(0,inplace=True)
merged_factors['article'].fillna(0,inplace=True)

In [21]:
merged_factors['news_coverage_flag'] = merged_factors['alert']+merged_factors['article']*3

In [22]:
merged_factors['news_coverage_flag']

0           6.0
1           0.0
2           0.0
3           0.0
4           3.0
5           0.0
6           0.0
7           0.0
8           6.0
9           9.0
10          0.0
11          0.0
12         14.0
13          0.0
14          0.0
15          0.0
16          0.0
17          0.0
18          3.0
19         12.0
20          0.0
21         46.0
22          0.0
23          0.0
24          0.0
25          0.0
26          0.0
27          0.0
28          0.0
29          0.0
           ...
4064804     0.0
4064805     0.0
4064806     0.0
4064807     0.0
4064808     0.0
4064809     0.0
4064810     0.0
4064811     0.0
4064812     0.0
4064813     0.0
4064814     0.0
4064815     0.0
4064816     0.0
4064817     0.0
4064818     0.0
4064819     0.0
4064820     0.0
4064821     0.0
4064822     0.0
4064823     0.0
4064824     0.0
4064825     0.0
4064826     0.0
4064827     0.0
4064828     0.0
4064829     0.0
4064830     0.0
4064831     0.0
4064832     0.0
4064833     0.0
Name: news_coverage_flag, Length: 4064834, dtype: float64

In [27]:
merged_factors_fillna = copy.deepcopy(merged_factors)
for signal in list(sentiment_factors.columns)[6:-1]:
    merged_factors_fillna[signal].fillna(merged_factors_fillna[signal].median())

In [28]:
with open('merged_factors.pkl','wb') as f:
    pickle.dump(merged_factors, f, pickle.HIGHEST_PROTOCOL)

In [31]:
with open('merged_fillna.pkl','wb') as f:
    pickle.dump(merged_factors_fillna, f, pickle.HIGHEST_PROTOCOL)

In [30]:
len(merged_factors_fillna.columns)

101